### PR TITLE
fix: reinclude server url in session url

### PR DESCRIPTION
**Pull request by obdulia-losantos**

### CODE REVIEW

**Comment by danse** [comment]
So @obdulia-losantos as we said, this won't allow us to develop with a remote server anyway. Do we still want to merge it?

**Comment by obdulia-losantos** [comment]
It makes more sense to include it than to ignore it. On the other side maybe it makes more sense to remove all the `couchdb` references and focus on `ums`

**Comment by obdulia-losantos** [comment]
Like here:
https://github.com/eHealthAfrica/angular-eha.user-management-auth#configuration

Maybe this should be:

```
app.config(function(ehaUserManagementAuthServiceProvider) {
  ehaUserManagementAuthServiceProvider.config({
    url: 'http://user-management-server.com',            // UMS server
    localStorageNamespace: 'myapp',    // Namespace for localstorage (default: lf)
    adminRoles: ['admin'],                  // 'Admin' role. (default: `['_admin']`)
    userRoles: ['reader', 'writer'],// Roles other than admin roles
    sessionEndpoint: '_session',            // Configurable session endpoint (default: `'_session'`)
    interceptor: {                          // Enable HTTP Interceptor (default: false)
      hosts: [                              // Configure hostnames that should be intercepted
        'http://mysecureserver.com'
      ]
    },
    defaultHttpFields: {                    // Passed through to Angular's $http config (default: unset)
      withCredentials: true                 // See: https://docs.angularjs.org/api/ng/service/$http#usage
    }
  });
});
```

**Comment by danse** [comment]
Okay i am adding it back here https://github.com/eHealthAfrica/angular-eha.user-management-auth/pull/4. i will also prepare another pull request where i will update the documentation about the options

**Comment by obdulia-losantos** [comment]
Close in favor of #4

**Pull request closed without merging**
